version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python main.py --mode api

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_URL=http://api:8080
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    command: streamlit run streamlit_app.py